name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Convert Excel to JSON
        run: npm run convert-excel

      - name: Create production environment file
        run: |
          cp src/environments/environment.ts src/environments/environment.prod.ts

      - name: Replace Firebase environment variables
        run: |
          sed -i "s/\\\${FIREBASE_API_KEY}/${{ secrets.FIREBASE_API_KEY }}/g" src/environments/environment.prod.ts
          sed -i "s/\\\${FIREBASE_AUTH_DOMAIN}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" src/environments/environment.prod.ts
          sed -i "s/\\\${FIREBASE_PROJECT_ID}/${{ secrets.FIREBASE_PROJECT_ID }}/g" src/environments/environment.prod.ts
          sed -i "s/\\\${FIREBASE_STORAGE_BUCKET}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" src/environments/environment.prod.ts
          sed -i "s/\\\${FIREBASE_MESSAGING_SENDER_ID}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" src/environments/environment.prod.ts
          sed -i "s/\\\${FIREBASE_APP_ID}/${{ secrets.FIREBASE_APP_ID }}/g" src/environments/environment.prod.ts
          sed -i "s/\\\${FIREBASE_MEASUREMENT_ID}/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g" src/environments/environment.prod.ts
          sed -i "s/production: false/production: true/g" src/environments/environment.prod.ts

      - name: Build Angular app
        run: npm run build:prod

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/drp-map/browser'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4